# Generated by Django 4.1.5 on 2023-03-04 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0167_module_status'),
        ('netbox_manage_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='dcim.device'),
        ),
    ]
