# Generated by Django 4.1.5 on 2023-03-04 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0167_module_status'),
        ('netbox_manage_project', '0002_alter_project_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='device',
        ),
        migrations.AddField(
            model_name='project',
            name='devices',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='dcim.device'),
        ),
    ]
