# Generated by Django 4.1.5 on 2023-03-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_manage_project', '0003_remove_project_device_project_devices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='devices',
        ),
    ]
