# Generated by Django 4.1.5 on 2023-03-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_manage_project', '0006_projectdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='device_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
