# Generated by Django 4.1.5 on 2023-03-06 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0034_standardize_description_comments'),
        ('ipam', '0063_standardize_description_comments'),
        ('netbox_manage_project', '0007_project_device_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='instance',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_instance', to='virtualization.virtualmachine'),
        ),
        migrations.AddField(
            model_name='project',
            name='instance_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ip_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ipaddress',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_ipaddress', to='ipam.ipaddress'),
        ),
    ]
